### ISSUE TITLE
Possible bug with  X_FORWARDED_FOR

### ISSUE THREAD

**Issue by geeklore** [woocommerce/woocommerce-gateway-payfast#1]
#### Affected ticket(s)

1876005-zen

#### Steps to reproduce the issue
Customer reports:

In the Payfast plugin, class-wc-gateway-payfast.php specifically, there is a bug with the is_valid_ip function. It was assessing the X_FORWARDED_FOR header as the $source_ip against the list of valid IPs. I've added `array_push($valid_ips, $source_ip);` to the if statement that adds support for X_FORWARDED_FOR, which fixes the issue. 

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by iamdharmesh** [comment]
Hi @geeklore, Thanks for reporting the issue. Can you please provide more details on the issue? So, I can check on it.
cc: @jeffpaul @dkotter

**Comment by dkotter** [comment]
Closing for now as unsure what the exact issue is here. It looks like support for `HTTP_X_FORWARDED_FOR` was added on purpose in v1.4.8 but that appears to be before the code was in this repo, so not exactly sure the purpose of it. If anyone has additional details on this issue or suggestions on fixes, we can reopen.
