### ISSUE TITLE
Orders stuck at Pending Payment when using reverse proxy

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/woocommerce-gateway-payfast#11]
**Describe the bug** 
WooCommerce PayFast plugin validates if ITN payment notification came from a legitimate source by comparing source IP with `payfast.co.za` servers. This automatically breaks payment notifications on all servers that use reverse proxy such as Cloudflare.

As a workaround, we're recommending the customers disable IP filtering with a custom code snippet which is neither secure nor easy to implement:

https://github.com/woocommerce/woocommerce-gateway-payfast/blob/master/includes/class-wc-gateway-payfast.php#L1227

I'd bring it up with the PayFast team to see if there's a better security mechanism we can use.

**To Reproduce**
1. Set up Cloudflare proxy on the server;
2. Purchase any product using Payfast payment gateway
3. Observe order status is still Pending Payment even though the payment went through

**Expected behavior**
Order status changes to Processing after successful payment.

**Comment by corsonr** [comment]
Any news?

**Comment by zwiesman31** [comment]
CC: @luizreis

**Comment by madeincosmos** [comment]
One more user possibly affected by this in 2629462-zen

**Comment by RiaanKnoetze** [comment]
Adding 2416714-zen

**Comment by dbfx** [comment]
Had this start happening today randomly - any IP changes happen?

**Comment by iamdharmesh** [comment]
I am not able to reproduce this issue. moving this to Backlog for now until we have some new reports for the same.

Thanks

**Comment by jeffpaul** [comment]
Closing as we're unable to replicate, if additional replication steps can be confirmed then please re-open and we'll continue triaging then... thanks!
