### ISSUE TITLE
Bump WordPress minimum to 6.1

### ISSUE THREAD

**Issue by vikrampm1** [woocommerce/woocommerce-gateway-payfast#111]
- [ ] Bump WordPress minimum to 6.1
- [ ] Scan for any conditional checks that may be in the code that can be removed with this minimum bump
- [ ] Check for any incompatible functionality with WP 6.1

**Comment by iamdharmesh** [comment]
Closing this as WordPress `Tested up to` version is already updated to **6.1** in  `trunk`. Please feel free to reopen if I misunderstood or missed anything here.
