### ISSUE TITLE
Update Payfast to match their new styling

### ISSUE THREAD

**Issue by jobthomas** [woocommerce/woocommerce-gateway-payfast#115]
Payfast updated their branding. This is where to find their new website. From what I can tell, these are the things that would need to be changed: 

https://payfast.io/logos-and-images/

* Logo (now adds "by network")
* Capitalisation: should be "Payfast" instead of "PayFast" (we have capital `F`)
* Colour palette

**Comment by ankitguptaindia** [comment]
Hi @dkotter Just to confirm, this issue has been moved to UAT but doesn't have any PR linked. Is it okay?

**Comment by dkotter** [comment]
@ankitguptaindia I've linked the PR that closes this out. It just updates text, so moved that straight to UAT
