### ISSUE TITLE
Compatibility testing with WooCommerce 7.6 RC and WordPress 6.2 RC

### ISSUE THREAD

**Issue by vikrampm1** [woocommerce/woocommerce-gateway-payfast#124]
With WooCommerce 7.6 RC 1 and WordPress 6.2 RC 1 releases out, perform the following:

- [ ] Test the extension thoroughly with WC 7.6 and WP 6.2
- [ ]  Add compatibility fixes, where necessary
- [ ]  Bump WooCommerce "Tested up to" to 7.6
- [ ]  Bump WooCommerce minimum to 6.8
- [ ]  Bump WordPress "Tested up to" to 6.2
- [ ]  Bump WordPress minimum to 5.8
- [ ]  Scan for any conditional checks that may be in the code that can be removed with this "Tested up to" and minimum bumps

Sample Changelog entry should then be:
> Dev - Bump WooCommerce minimum supported version from X.X to 6.8.
> Dev - Bump WooCommerce "tested up to" version 7.6.
> Dev - Bump WordPress minimum supported version from X.X to 5.8.
> Dev - Bump WordPress "tested up to" version 6.2.

**Comment by kirtangajjar** [comment]
# Checklist

- [ ] Set up Payment Gateway with sandbox credentials
- [ ] Place an order with the PayFast payment gateway.
- [ ] Place an order for a subscription product with the PayFast payment gateway and renew the subscription.
