### ISSUE TITLE
Add "Split Payments"

### ISSUE THREAD

**Issue by corsonr** [woocommerce/woocommerce-gateway-payfast#13]
PayFast recently introduced **Split Payments** and a couple of our customers requested we implement this feature so that they use it in conjunction with Vendors.

- https://www.payfast.co.za/2019/10/23/payfast-launches-split-payments/

It would be nice to consider it since we don't have that many options for vendors.

**Comment by iamdharmesh** [comment]
Hi @corsonr,

Thanks for report the issue. Can you please help to provide more detailed feature requirements? 

Thanks
cc: @jeffpaul @dkotter

**Comment by jeffpaul** [comment]
Closing this as a feature enhancement that's being currently tracked in the WooCommerce ideas board --> https://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/40333552-split-cart-payment-for-payfast-gateway
