### ISSUE TITLE
`build` directory not included in 1.5.5 archive - WooCommerce Blocks integration is broken

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-gateway-payfast#145]
The zip folder released for 1.5.5 does not contain the `build` directory, this causes the code for WooCommerce Blocks to not be loaded thus preventing the gateway registering with the Cart and Checkout blocks.

Not sure what the cause was but it'd be great if we could run another release and include it!

**Comment by vikrampm1** [comment]
[1.5.6](https://github.com/woocommerce/woocommerce-gateway-payfast/releases/tag/1.5.6) released that contains the build directory. Hence closing this issue.
