### ISSUE TITLE
Payfast not supported in checkout block on lastest hosted version

### ISSUE THREAD

**Issue by mdmoore** [woocommerce/woocommerce-gateway-payfast#161]
### Describe the Bug
Payfast isn't appearing in the checkout block on the latest hosted(Atomic) version. When editing a page that includes the checkout block, a message appeared stating that Payfast doesn't support the checkout block. After deleting the hosted plugin and installing the latest download from WooCommerce.com, Payfast appears in the checkout block.

This is similar to https://github.com/woocommerce/woocommerce-gateway-payfast/issues/46, however the `build` directory does appear to be present in this case.

Reported here - p1696930151758429-slack-C7U3Y3VMY

### To Reproduce

1. Install the hosted Payfast plugin on a WordPress.com site.
2. Set the WooCommerce currency to Rand
3. Configure the Payfast settings
4. Create a checkout page using the checkout block
5. Add a product to the cart and view the checkout page
6. Notice that Payfast doesn't appear as a payment method
7. Compare to a shortcode checkout where Payfast does appear

### Expected Behavior

Payfast should be compatible with the checkout block on WordPress.com sites.

### Actual Behavior

Payfast doesn't appear in the list of of payment methods on the checkout block.

### Environment

 - WordPress Version - 6.3.1
 - WooCommerce Version - 8.2.0
 - Plugin Version - 1.5.9
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

**Comment by a-danae** [comment]
Also reported in https://github.com/woocommerce/woocommerce-blocks/issues/11195 by @raifd , 7137561-zd-a8c

**Comment by jeffpaul** [comment]
@mdmoore @a-danae how urgent a request is this?  I ask as we're currently loaded with some other high priority tasks and projects, so I only want to figure out how to interrupt those if there's an immediate/urgent need for this on PayFast.

**Comment by a-danae** [comment]
I'll defer this question to @diegocurbelo , as I'd need a better picture of the rest of the priorities to answer.

**Comment by Sidsector9** [comment]
I am unable to reproduce the issue on local setup.
@mdmoore @diegocurbelo is it possible to have access to the Atomic site or Woo Express so that we can debug this?

**Comment by diegocurbelo** [comment]
> I am unable to reproduce the issue on local setup. @mdmoore @diegocurbelo is it possible to have access to the Atomic site or Woo Express so that we can debug this?

Hey @Sidsector9, you can [create a WooExpress test site here](https://woo.com/express/) for free

**Comment by Sidsector9** [comment]
@diegocurbelo the free trial doesn't allow to upload plugins, is there something I might be missing?

**Comment by Sidsector9** [comment]
Hey @diegocurbelo just following up with the last conversation.

**Comment by diegocurbelo** [comment]
> Hey @diegocurbelo just following up with the last conversation.

I created a test site (valid for 7 days) and added you as an administrator... you should have received the login credentials in your GitHub email.

**Comment by Sidsector9** [comment]
Hi all, this seems to be working now, please watch the video below:


https://github.com/woocommerce/woocommerce-gateway-payfast/assets/17757960/022dc096-5e03-425f-9d72-988eb119ea47

cc: @vikrampm1 @jeffpaul

**Comment by mdmoore** [comment]
Hey @Sidsector9! Thanks for working on this. This issue is only present with hosted Payfast extension which is installed on Atomic sites when installing from the plugins page. When uploading the package from Woo.com, everything works as expected. I've created a site and added you as admin with the hosted Payfast plugin installed and configured. You should have an email now. 

Shortcode checkout is working as expected.

Here's what we see on the checkout block: 

![image](https://github.com/woocommerce/woocommerce-gateway-payfast/assets/3473953/bd1527ce-d21d-4997-9d26-019404436fd2)

And in the checkout page editor: 

<img width="400" src="https://github.com/woocommerce/woocommerce-gateway-payfast/assets/3473953/1d907ad8-e1f0-48ed-89cf-587ff0eb4330" />

**Comment by Sidsector9** [comment]
Thanks for the feedback @mdmoore.
@diegocurbelo added me an admin on https://unlikely-hideout-alpaca.atomicsites.blog/, this is the only login details I received.

These are the steps I followed:

1. Installed WooCommerce and Payfast from the plugins page (see image below)

<img width="1103" alt="Screenshot 2024-01-22 at 10 03 02 AM" src="https://github.com/woocommerce/woocommerce-gateway-payfast/assets/17757960/33970cb7-e09a-40e0-8643-e30ddc49e963">

2. Switched the currency to South African Rand.
3. Connected Payfast using the sandbox keys and activated the plugin and activated the gateway.

I am unable to reproduce both the issues. Can you kindly verify if I'm following the steps correctly?

**Comment by mdmoore** [comment]
@Sidsector9 was able to reproduce the issue and found that JS assets aren't being loaded. The `index.js` file is trying to load from the `wp-content/plugins/1.6.1` path, which doesn't exist.

**Comment by Sidsector9** [comment]
@mdmoore just following up on this. Did Woo find the solution to this?

**Comment by sukafia** [comment]
7832210-zen

**Comment by vikrampm1** [comment]
@mdmoore this is currently blocked and awaiting your response.

**Comment by Sidsector9** [comment]
Adding a video here that shows the issue only occurs when installing directly from the plugins repo - https://drive.google.com/file/d/1EYnnNg56YRpA7AbJI7sG4VvUQyenOepx/view?usp=sharing
