### ISSUE TITLE
Incompatible with WooPayments multi currency

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce-gateway-payfast#167]
### Describe the Bug

With Payfast and WooPayments (with multi-currency enabled) on the same site, Payfast doesn't show up as a payment method on the checkout page.

### To Reproduce

1. Install and activate WooPayments. Enable multi-currency and add a currency other than Rand
2. Payfast is not available at checkout :(

### Expected Behavior

For Payfast to still show up, at least if the order currency is Rand.

### Actual Behavior

Payfast doesn't show up.

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>
  
  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by vikrampm1** [comment]
@peterwilsoncc might also need to look into this when you're back on the WooPayments compat testing cc @jeffpaul
