### ISSUE TITLE
Test Integration with Cart and Checkout Blocks

### ISSUE THREAD

**Issue by vikrampm1** [woocommerce/woocommerce-gateway-payfast#176]
Test integration with block based checkout and full site editing with the following tasks:

- [x] Compatible - This extension is [already declared compatible with Cart and Checkout Blocks](https://woo.com/document/cart-checkout-blocks-status/?quid=e9af6e286d78cbf1965f9db8f4f89766#section-10).  
- [ ] Integration - Each extension integrates natively with Cart and Checkout Blocks and Store Editing (uses blocks, provides no-code customization options, etc).
- [ ] Investigate and add any missing e2e test cases to cover Cart and Checkout Blocks.
- [ ] Add integration fixes, where necessary.

**Comment by jeffpaul** [comment]
@Sidsector9 note that you'll want to capture #161 in your research/updates as part of this project thread

**Comment by Sidsector9** [comment]
- [x]  Block Checkout works as expected
- [x]  Block Cart works as expected
- [x]  Store editing works as expected
- [x] Has E2E coverage 

---

- ✅  The Cart and Checkout Blocks display all the necessary information related to the extension

---

- The plugin does not have any shortcodes.
- Investigating further, I did not find any more features that needs support on the Cart and Checkout block pages.

> [!IMPORTANT]
> **[Non-blocker]**: We have issue #161 where Payfast isn't working only on Atomic sites. We're waiting for access to the Atomic site to debug further.

---

**Comment by jeffpaul** [comment]
@Sidsector9 can you add the note/section to the readme(s) noting the compat here?
