### ISSUE TITLE
Update plugin's main to match with repo's slug

### ISSUE THREAD

**Issue by diegocurbelo** [woocommerce/woocommerce-gateway-payfast#178]
### Describe the Bug

Currently plugin's main file is `gateway-payfast.php` while the repo's slug is `woocommerce-gateway-payfast`.

We need to keep the current file for compatibility, like it was done [here for GoCardless](https://github.com/woocommerce/woocommerce-gateway-gocardless/commit/4c22b87901065af376d97d334317ddfc251959c2)

**Comment by vikrampm1** [comment]
@dkotter I think we can pick this up while preparing the next release.
