### ISSUE TITLE
Update Express Payment buttons to match incoming WooCommerce standard

### ISSUE THREAD

**Issue by vikrampm1** [woocommerce/woocommerce-gateway-payfast#183]
### Describe the bug

WooCommerce is in the process of rolling out new standards and expectations for how express payment buttons should be displayed on product, cart and checkout pages. These new standards will affect how payment gateways display these payment buttons to ensure some consistency and prevent a mismatch of styles, sizes and placement that can occur if you have multiple payment options. eg

<p align="center">
<img width=400px src="https://github.com/woocommerce/woocommerce-square/assets/8490476/a95e9ed6-6cc9-4c82-b621-fedf0a893205" />
</p>

The WooPayments and the Stripe plugins have updated to these new standards as they are being confirmed. The PayFast plugin should update its express payment buttons to align with these new standards too. 

### Product page

| Before | After |
|--------|--------|
| <img width="400" alt="image" src="https://github.com/woocommerce/woocommerce-square/assets/8490476/17cb3db8-f588-4e9f-bdbb-eccdf4d6137f"> | <img width="400" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/a07f8a59-2607-4a63-a0b3-f954d59f4728" /> | 

- [ ] Move express button to below _Add to cart_ button.
- [ ] Remove **- OR -**
- [ ] Remove the margins on the element.
 
### Cart page

| Before | After |
|--------|--------|
| <img width="1095" alt="image" src="https://github.com/woocommerce/woocommerce-square/assets/8490476/8c54a6f5-2755-4564-8415-d3d0f7340d85"> | ![image](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/500a4a33-58b3-44f1-b649-57df92e761d7) | 

- [ ] Move express button to below _Proceed to checkout_ button.
- [ ] Remove **- OR -**
- [ ] Remove the margins on the element.

WooPayments and Stripe made similar changes. You can find the changes they made here https://github.com/Automattic/woocommerce-payments/pull/6985 and here https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2782/https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2783. 

The default button hight WooCommerce will be standardising is 48px.

### Expected behavior

While we wait for the full set of WooCommerce guidelines to be approved and rolled out, PayFast's Express payment buttons (Apple Pay and Google Pay) can be updated fairly easily in the mean time to prevent inconsistencies.

**Comment by peterwilsoncc** [comment]
Payfast doesn't add any express pay buttons, closing this ticket as unplanned.
