### ISSUE TITLE
Payfast incorrect API response handling for subscription renewal payments

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce-gateway-payfast#2]
Affected ticket: 1766027-zen

The user in the ticket contacted us regarding the responses in a subscription renewal being handled incorrectly.

The response they receive in this case is:

```
{
	"code":200,
	"status":"success",
	"data":{
		"response":"05",
		"message":"Your card was not accepted for payment. Please try the transaction again. If the error persists, please consult your issuer\/bank for more information (05)"
	}
}
```

If we compare that to a successful subscription renewal this is what they receive:

```
{
	"code":200,
	"status":"success",
	"data":{
		"response":"true",
		"message":"Transaction was successful (00)"
	}
}
```

As we can see in both these cases the code = 200 and the status = success. The documentation doesn't clarify how card errors are handled, see: https://developers.payfast.co.za/documentation/#ad-hoc-payments-api-endpoints
It only mentions how to handle errors that are handled when the API request is invalid. Since it's returning a 200 response in this case it doesn't check whether there is any card error.

The following code handles the response: https://github.com/woocommerce/woocommerce-gateway-payfast/blob/1.4.11/includes/class-wc-gateway-payfast.php#L990-L1004
As we can see there it will only return an error if the code != 200 or status = failed. Otherwise it will return true which causes the subscription payment to be renewed even though it did return a card error.

I'm not able to reproduce this type of response with a sandbox account, so it might be best to clarify this directly with PayFast.

The user in the ticket suggested the following changes:

```
WooCommerce PayFast Gateway Plugin patches: 
Changed line 990 - 992 of class-wc-payfast-gateway.php file (now line 990 - 997, original lines were not existent) 
From First Patch (mid January): 
/* Little Hack */ 
$apiArgsJson = json_decode($api_args['body']['item_description'], true); 
$this->log( "PayFast API response for renewal order ID " . $apiArgsJson['renewal_order_id'] . ":n" . print_r($results['body'], true) ); 

To Now (31st January): 
/* Little Hack By Realmdigital */ 
$apiArgsJson = json_decode($api_args['body']['item_description'], true); 
if ( is_wp_error($results) ) { 
$errorMessage = $results->get_error_message(); 
} else { 
$errorMessage = print_r($results['body'], true); 
} 
$this->log( "PayFast API response for renewal order ID " . $apiArgsJson['renewal_order_id'] . ":n" . $errorMessage );

​​Changed line 1001 of class-wc-payfast-gateway.php file (now line 1006, original lines were 997) 
From Original: 
if ( ! is_null( $maybe_json ) && isset( $maybe_json['status'] ) && 'failed' === $maybe_json['status'] ) {

To First Patch (mid January): 
if ( ! is_null( $maybe_json ) && isset( $maybe_json['data'] ) && ('failed' === strtolower($maybe_json['data']['message']) || 'failure' === strtolower($maybe_json['data']['message']) ) ) {

To Now (31st January): 
if ( ! is_null( $maybe_json ) && isset( $maybe_json['data'] ) && (isset($maybe_json['code']) && $maybe_json['code'] !== 200) ) {

Changed line 1005 of class-wc-payfast-gateway.php file (now line 1010, original lines were 1001) 
​ From Original: 
return new WP_Error( $maybe_json['code'], trim( $maybe_json['data']['message'] ), $results['body'] );

To Now (31st January): 
return new WP_Error( $maybe_json['code'], trim( $maybe_json['data']['result'] ), $results['body'] );
```

**Comment by tommyshellberg** [comment]
Any update on this one @JGPage?

**Comment by JGPage** [comment]
@tommyshellberg A fix is pending, just needs to be done on the public repo

https://github.com/woocommerce/woocommerce-gateway-payfast-private/pull/64#issuecomment-488301042

**Comment by allendav** [comment]
Any updates @JGPage  ?

**Comment by RheinhardtSnyman** [comment]
Hi @allendav, pull request https://github.com/woocommerce/woocommerce-gateway-payfast/pull/6 has been made with the fix which needs to be merged.

**Comment by dwainm** [comment]
Fixed in https://github.com/woocommerce/woocommerce-gateway-payfast/pull/6
