### ISSUE TITLE
Error is an Object and can't be converted to a string

### ISSUE THREAD

**Issue by mdmoore** [woocommerce/woocommerce-gateway-payfast#20]
**Describe the bug**
When a subscription renewal payment fails due to insufficient funds, PayFast returns an error.  It looks like an object is returned, leading to this error: 

```
CRITICAL Object of class stdClass could not be converted to string in /usr/www/users/curiousunp/wp-content/plugins/woocommerce-payfast-gateway/includes/class-wc-gateway-payfast.php on line 879
```

**To Reproduce**
I'm not sure how to reproduce an insufficient funds failure in Payfast.  

**Expected behavior**
An error be interpreted an printed to the order notes up status change.

**Screenshots**

**Environment (please complete the following information):**
 - WordPress Version - 5.4.2
 - WooCommerce Version - 4.0.1
 - PayFast Plugin Version - 1.4.15

3079584-zd

**Comment by tsetend** [comment]
The user came back to get an update on this issue: 3079584-zen

**Comment by kylemcph** [comment]
I'm closing the 3079584-zen ticket instead of continually putting it on-hold. We can create a new follow-up once resolved.

**Comment by bernattorras** [comment]
Another customer reporting this issue here: 3283541-zen

It seems that it can be replicated there if you try to "Retry the renewal payment" on a subscription. 

Here's all the information that is logged in the Payfast logs:

```
09-03-2020 @ 15:03:02 - Attempting to renew subscription from renewal order 6818
09-03-2020 @ 15:03:04 - Error posting API request:
stdClass Object
(
    [code] => 06
    [reason] => An error occurred processing the payment, please try again. If the error persists, please contact your bank for more information. (06)
)
```

I've used "Health Check" to temporarily disable all plugins except WC, WCS, and PayFast, but the issue persists (I'm not sure though if Health Check is really disabling the plugins during this request).

I've also asked the customer to enable WP_DEBUG_LOG and replicate the issue again to see if we can get more details about this error...

**Comment by bluekable** [comment]
I started receiving this error recently and did some digging - here are my findings:

The logged error in debug file was this:
[05-Oct-2020 09:37:37 UTC] PHP Recoverable fatal error:  Object of class stdClass could not be converted to string in /usr/www/users/iiconnupus/wp-content/plugins/woocommerce-payfast-gateway/includes/class-wc-gateway-payfast.php on line 879

That line is:

`$renewal_order->update_status( 'failed', sprintf( __( 'PayFast Subscription renewal transaction failed (%1$s:%2$s)', 'woocommerce-gateway-payfast' ), $response->get_error_code() ,$response->get_error_message() ) );
`

And its the last param, the call to $response->get_error_message that is failing.

I traced it back to what the OP here mentioned in that on line 999 of the same file in api_request method a WP_Error is returned. It's constructor requires the following params:

`* @param string|int $code    Error code.
  * @param string     $message Error message.
  * @param mixed      $data    Optional. Error data.`

However it is being assed a stdClass as the second param for $message.

Changing line 999 to the below for me helped but I am not sure of how WC wants to deal with such errors from PayFast so its one possible solution but may not be the one you guys prefer.

`return new WP_Error( json_decode( $results['body'] )->data->response->code, json_decode( $results['body'] )->data->response->reason, $results );
`

The specific changes were in accessing the code and the message/reason in the response's stdClass. Attached is a screen grab of the structure of the response from Payfast.

<img width="865" alt="Screenshot 2020-10-05 at 12 16 25" src="https://user-images.githubusercontent.com/19387010/95067788-9d954080-0704-11eb-8d2e-8093cb184a0a.png">

**Comment by thuautp** [comment]
also seen in 3375962-zen

**Comment by ldr2273** [comment]
Customer in 3283541-zen has reached out for a follow up on this. Pinged dev channel to see if we could get a look at this.

**Comment by zdenys** [comment]
Another case in 25401880-hc.
