### ISSUE TITLE
Release 1.4.17

### ISSUE THREAD

**Issue by luizreis** [woocommerce/woocommerce-gateway-payfast#27]
We should release `1.4.17` to account for the compatibility tests run in https://github.com/woocommerce/woocommerce-gateway-payfast/issues/25 with `WP 5.6`, `WC 4.7.0` and `PHP 8.0.0`.

We should also strive to include some fixes and PRs that are currently open.

cc @dwainm

**Comment by dwainm** [comment]
Thank you @luizreis

**Comment by luizreis** [comment]
Released with `woorelease` after merging #18. All went well during release and smoke tests worked fine.
