### ISSUE TITLE
[Google Analytics] PayFast overrides the previous referrer, breaking conversion tracking

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/woocommerce-gateway-payfast#4]
#### Affected ticket(s)
1290308-zen

#### What I expected
To track purchase conversions with Google Analytics. 

#### What happened instead
As the checkout process redirects to PayFast, it overrides the previous referrer in Google Analytics making it impossible to track conversions.

PayPal Standard has it solved by adding `utm_nooverride=1` to redirect page URL:

https://github.com/woocommerce/woocommerce/blob/3.4.3/includes/gateways/paypal/includes/class-wc-gateway-paypal-request.php#L120

PayFast does not have any similar measures and redirects to Thank You page without additional parameters:

https://github.com/woocommerce/woocommerce-gateway-payfast/blob/1.4.9/includes/class-wc-gateway-payfast.php#L324

As we have two official Google Analytics plugins, it's worth adding this parameter to measure conversions.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by paulka007** [comment]
This can be done by adding an Exclusions in Google Analytics : http://blog.analytics-toolkit.com/2015/payment-gateway-referrer-exclusions-google-analytics/

But being automatic would be better.
