### ISSUE TITLE
Update PayFast user card details using token

### ISSUE THREAD

**Issue by JDSymington** [woocommerce/woocommerce-gateway-payfast#41]
_**Some background info**_
I'm using Woocommerce Subscriptions plugin and  Woocommerce Membership plugin with Woocommerce PayFast plugin as the only payment method. Members sign up for a subscription plan of their choice with no expiration date. A user is only allowed one subscription to one plan. It they decide to switch to another plan, the current one is cancelled and they pay a small switching fee. This works perfectly until the user has to update their credit card details.

_**Problem statement**_
When the user's credit card expires the next ad hoc payment fails.

The order's status changes to "Payment pending" as shown in the screenshot.
![Screenshot 2021-04-01 105653](https://user-images.githubusercontent.com/30504052/113270343-a775b600-92d9-11eb-8bb1-ed5f6855874f.png)

Their subscription is then placed on hold immediately which also pauses the linked membership.
![Screenshot 2021-04-01 105733](https://user-images.githubusercontent.com/30504052/113270265-93ca4f80-92d9-11eb-86f0-6f46c0d8dcf6.png)

When a user clicks the "PAY" button for the pending order they are taken to the following screen:
![Screenshot 2021-04-01 105919](https://user-images.githubusercontent.com/30504052/113270360-ac3a6a00-92d9-11eb-8c85-766b674c81e0.png)

Now the only solution is for the user to cancel the subscription and sign up again. This is very bad for customer satisfaction and they have to pay the sign up fee again.

_**Proposed solution**_
On the PayFast developers page they describe a way of updating a buyer's card details on Tokenization charges using a link that will redirect them to PayFast in order to perform the update.
[PayFast Recurring Card Update](https://developers.payfast.co.za/docs#recurring_card_update)

The user is taken to this page to update their details:
![Screenshot 2021-04-01 120657](https://user-images.githubusercontent.com/30504052/113278952-d3496980-92e2-11eb-9687-6cee1293be5f.png)

It would probably be the best solution to add a button that a user can click to retrieve the token and take them to PayFast to update the card details.

**Comment by jessepearson** [comment]
This is closely related to #32 and both could likely be worked on at the same time. 

@JDSymington Can you confirm how often a situation like this happens to your customers?

**Comment by JDSymington** [comment]
@jessepearson this happens to every customer whos credit card expires.
My workaround has been to monitor any failed payments and then manually send the customer an email with a link I generate for them to update the card details. This is however not a solution just a very temporary workaround.

**Comment by jessepearson** [comment]
@JDSymington Thanks for the follow up. I bumped up the priority on this for the team to take a look.

**Comment by PallookaJ** [comment]
@jessepearson I originally logged #32 and agree that the proposed solution above would work for us too. Even better would be to load the card update URL in an iframe so that the user isn't redirected away from our site. At the moment we have about 20-30 users a month that either have their cards expire or have to update their card details for some other reason. (like card having been cancelled, moving banks etc.)

Just a thought but the plugin already receives the unique card update URL when a payment fails and writes it in the log. Would this not be the easiest place to pull the needed from?

**Comment by JDSymington** [comment]
@PallookaJ I also thought about using the update URL returned by the failed payment. There is a big downside to this though.
If generating the URL on the fly a user can also update card details for a subscription that hasn't failed yet (for example if they own two credit cards and want to move the subscription from the one card to the other).
Using the URL returned by the failed payment will force a user to wait for the payment to fail first.

**Comment by JDSymington** [comment]
Hi. I just want to follow up on this issue.
Is there a proposed solution yet?

**Comment by JDSymington** [comment]
@jessepearson my user base has grown quite significantly since I opened this issue.
If there's any developer keen to work on this I'm willing to pay. Unfortunately if I can't solve this problem I'll have to move to another gateway.

**Comment by iamdharmesh** [comment]
@JDSymington @PallookaJ @jessepearson
PR for issue #32 is created and it also fixes this reported issue. Apart for fix manual payment, it also adds the functionality of `Change Payment Method`, which provides functionality to change the payment method of subscription at any time. So, I believe the **update user card details** feature is no longer needed. Can you please share your feedback on this for the same?

Thanks.
cc: @jeffpaul @dkotter

**Comment by JDSymington** [comment]
@iamdharmesh I agree that the **Update User Card Details** feature won't be needed if the **Change Payment Method** feature is implemented as the two features basically perform the same task.

Thank you very much.

Do you have any idea when this will be released?

**Comment by jeffpaul** [comment]
@JDSymington the PR noted is currently in QA testing, still needs to go through Code Review, Regression Testing, UAT, and then Smoke Testing before being cleared for release.  I would estimate that'll happen somewhere around late March / early April as a very rough estimate.

**Comment by ankitguptaindia** [comment]
**Update -**  Above issue is addressed in connected PR. New customers' reports of this issue can be tested/verify with this **Development version** of the plugin.

[woocommerce-gateway-payfast.zip](https://github.com/woocommerce/woocommerce-gateway-payfast/files/8652067/woocommerce-gateway-payfast.zip)



**_Please Note that this is Dev version of the plugin file and ONLY has fixes related to the above issue so other fixes might not work with this dev version of the plugin. It is also recommended that, Don't use this plugin file on the Production/Live site. This is just for testing purposes only_**
