### ISSUE TITLE
Update Compatibility with WooCommerce

### ISSUE THREAD

**Issue by ryanr14** [woocommerce/woocommerce-gateway-payfast#47]
**Describe the bug**
When I click to update WooCommerce I get the following notification:

The following active plugin(s) have not declared compatibility with WooCommerce 5.0 yet and should be updated and examined further before you proceed.

**Expected behavior**
It should declare support for the current version(s) of WooCommerce. :)

**Screenshots**
<img width="295" alt="Markup%202021-10-11%20at%2022 28 32" src="https://user-images.githubusercontent.com/867748/136880969-14b14811-4fdf-4182-b24d-9f093a37e5a7.png">

**Comment by joashrajin** [comment]
+1 4686053-zd-woothemes

**Comment by sulemanhelp** [comment]
@ryanr14 support for current woocommerce is already added and released. 

https://github.com/woocommerce/woocommerce-gateway-payfast/pull/60
