### ISSUE TITLE
Better handling of on hold tokens

### ISSUE THREAD

**Issue by dwainm** [woocommerce/woocommerce-gateway-payfast#5]
When a renewal is submitted and fails, PayFast places the token into an on hold state and returns 400 error on our API call. We should handle this in a way that gives the admin/shop_manager a better idea of the steps to take next.

**Comment by iamdharmesh** [comment]
Hi @dwainm @roykho,

Can you please provide more information on **on-hold tokens**?(as I didn't found anything about on-hold token on payfast developer docs)
Also, as mentioned by @jacoswan, can you please help to check and confirm if this issue is similar to #32.

Thanks
cc: @jeffpaul @dkotter

**Comment by jeffpaul** [comment]
@iamdharmesh I believe those two issues are related, yes, so feel free to work on a fix that handles both together in an "improves error handling" sort of way.

**Comment by jeffpaul** [comment]
@dwainm note that we're proceeding with our best assumption that the work in #32 will close out this issue.  If that's not accurate, if we're misunderstanding things, then please share additional information to help clarify... thanks!

**Comment by ankitguptaindia** [comment]
**Update -**  Above issue doesn't have much information to reproduce/test. We are assuming the connected PR will resolve this scenario mentioned in the description _(as we worked on similar scenario in connected PR)._  

If connected PR doesn't resolve above scenario then please feel free to mention here with detailed info. You can test new changes by using below zip file quickly. 

[woocommerce-gateway-payfast.zip](https://github.com/woocommerce/woocommerce-gateway-payfast/files/8652067/woocommerce-gateway-payfast.zip)



**_Please Note that this is Dev version of the plugin file and ONLY has fixes related to the above issue so other fixes might not work with this dev version of the plugin. It is also recommended that, Don't use this plugin file on the Production/Live site. This is just for testing purposes only_**
