### ISSUE TITLE
Add filters to make it compatible with other plugins

### ISSUE THREAD

**Issue by mohammaddanish-cedcoss** [woocommerce/woocommerce-gateway-payfast#62]
We are making payfast plugin compatibility with other plugin
so we need a filter in the following place to handle the payment options in payfast on checkout.

In your plugin file /include/class-wc-gateway-payfast.php
we need a filter within ‘order_contains_subscription’ function
like return apply_filters(‘order_contains_subscription’, wcs_order_contains_subscription( $order ) );

For Example,

	public function order_contains_subscription( $order ) {
		if ( ! function_exists( 'wcs_order_contains_subscription' ) ) {
			return false;
		}
		return apply_filters( 'order_contains_subscription', wcs_order_contains_subscription( $order ) );
	}

**Comment by jeffpaul** [comment]
@mohammaddanish-cedcoss thanks for the report, we'll review how best your suggested filter works and get back to you with any questions or concerns.

**Comment by iamdharmesh** [comment]
Hello @mohammaddanish-cedcoss,

Thanks for the report. can you please provide more details on your use case here? because `order_contains_subscription()` directly returning response of WooCommrce subscriptions' function (`wcs_order_contains_subscription`) without any operation on it. So, I think a better approach here is to check for filters in `wcs_order_contains_subscription` if it satisfies your need or not.

Thanks.

**Comment by mohammaddanish-cedcoss** [comment]
Thank you for your reply.
We have a plug-in called Subscriptions For WooCommerce on the WordPress Org. We are making it to compatible with your payment gateway. But the problem is that you are using this function order_contains_subscription to add  'subscription_type'  in the payfast_args_array to make a payment and then it returns an array of response with a token. And we need this token to make a payment on a recurring.

If you know any other way how can I do it then please let me know?

**Comment by iamdharmesh** [comment]
Thanks for providing more information @mohammaddanish-cedcoss. For this, I think it's better to add a filter on `$this->data_to_send` array. I will add it and will update it here for the same.

Thanks.

**Comment by mohammaddanish-cedcoss** [comment]
Yeah sure, Thank you very much
