### ISSUE TITLE
Add post purchase hooks

### ISSUE THREAD

**Issue by malithsen** [woocommerce/woocommerce-gateway-payfast#67]
Developer in 4821742-zd-woothemes requests two hooks that would allow merchants and tools to create post-purchase offers and implement one-click upsell.

> So here is the situation. We provide services to businesses to create sales funnels, and one of the prime requirements of a sales funnel is to allow one-click post-purchase offers. But this requires specific reference transaction API(s), which is not supported by most payment gateways, thus limiting the number of payment gateways people can use.

They've sent us the following doc with their suggested changes
[hooks details.pdf](https://github.com/woocommerce/woocommerce-gateway-payfast/files/8178768/hooks.details.1.pdf)

**Comment by jeffpaul** [comment]
@malithsen seems reasonable and worthwhile, will add to our backlog.  If the developer has a hard time constraint please let us know, otherwise we'll get to this.

**Comment by tuhindewan** [comment]
@jeffpaul  thank you for consideration. Please let us know, if you need further information.

**Comment by iamdharmesh** [comment]
Hi @dkotter @jeffpaul, 

Two actions/filters are requested in this issue. 1 requested filter is already added in PR #64 and another requested action hook is added in PR #67.

Thanks.
cc: @malithsen
