### ISSUE TITLE
Add action to make it compatible with other plugins

### ISSUE THREAD

**Issue by tuhindewan** [woocommerce/woocommerce-gateway-payfast#69]
**Is your feature request related to a problem? Please describe.**
I would like an action to be called after completion of the payment request.

**Describe the solution you'd like**
**handle_itn_payment_complete()** method is called when payment request status is "complete". 
It would be nice if you could add an action inside the **handle_itn_payment_complete()** method,
after this code -> $order_id = self::get_order_prop( $order, 'id' );

**Additional context**
we need action in order to make additional or custom features that will make PayFast compatible with other custom plugins.

**Comment by jeffpaul** [comment]
@tuhindewan can you provide an example of what custom feature might be added using that action?

**Comment by tuhindewan** [comment]
@jeffpaul Here's how it will work:
1. A user will buy a product on our site through a regular checkout process.
2. Right after the checkout, before order confirmation, we will offer him an upsell offer.
3. This will be a one-click upsell offer, i.e., the buyer will be able to accept the offer through a click of a button, but not go through the checkout process again. Or, he can reject the offer if he wants to.
4. We will then offer him another similar offer.
5. Finally, he will go to the thank you page for order summary and confirmation.

In step 3, we need to use token or Marchant's basic information temporarily. This action will provide us to access $data and $order variables in which we will get our required values.

**Comment by iamdharmesh** [comment]
Hi @tuhindewan,

Thanks for reporting the issue. The action hook requested here is looking very similar to the request in #67 for the post-purchase hook, can you please confirm if it's same and check if PR created for that also fulfills your requirement.

Thanks.
cc: @jeffpaul
