### ISSUE TITLE
Add support for Transaction ID

### ISSUE THREAD

**Issue by conschneider** [woocommerce/woocommerce-gateway-payfast#72]
Add support for transaction IDs based on: https://developer.woocommerce.com/2014/08/05/wc-2-2-payment-gateways-adding-refund-support-and-transaction-ids/

Change: https://github.com/woocommerce/woocommerce-gateway-payfast/blob/8304af638d2635f84e68627b63d20deb86e7aeef/includes/class-wc-gateway-payfast.php#L680

```
		/* translators: 1: gross amount 2: payment id */
				$order->add_order_note( sprintf( __( 'PayFast pre-order product line total paid: R %1$s (%2$s)', 'woocommerce-gateway-payfast' ), $data['amount_gross'], $data['pf_payment_id'] ) );
				$order->payment_complete();
				$this->cancel_pre_order_subscription( $token );
			}
		} else {
			$order->payment_complete();
		}
```

to: 

```
	/* translators: 1: gross amount 2: payment id */
				$order->add_order_note( sprintf( __( 'PayFast pre-order product line total paid: R %1$s (%2$s)', 'woocommerce-gateway-payfast' ), $data['amount_gross'], $data['pf_payment_id'] ) );
				$order->payment_complete( $data['pf_payment_id'] );
				$this->cancel_pre_order_subscription( $token );
			}
		} else {
			$order->payment_complete( $data['pf_payment_id'] );
		}
```

Discussion: https://wordpress.org/support/topic/needing-to-add-payfast-payment-transaction-id/#post-15472997

Thanks,

**Comment by robindevitt** [comment]
I originally posted the issue in the [discussion link](https://wordpress.org/support/topic/needing-to-add-payfast-payment-transaction-id/#post-15472997).

Im happy to create a PR and submit that if it's of any help?
