### ISSUE TITLE
Support for Multiple Subscriptions

### ISSUE THREAD

**Issue by csmcneill** [woocommerce/woocommerce-gateway-payfast#76]
**Is your feature request related to a problem? Please describe.**

On [this page](https://woocommerce.com/document/subscriptions/payment-gateways/#:~:text=%E2%9C%94-,PayFast,-%E2%80%93), PayFast is not listed as a gateway that is capable of being able to process multiple subscriptions at once.

https://woocommerce.com/document/subscriptions/develop/multiple-subscriptions/

**Describe the solution you'd like**

If this is a limitation of the gateway, as opposed to a limitation of PayFast as a processor, it would be great if it could support the purchase of multiple subscriptions.

**Additional context**

4910698-zen

**Comment by nicholasjeberlin** [comment]
+1 35235399-hc

**Comment by f-camara** [comment]
+1

**Comment by iamdharmesh** [comment]
I got a chance to check on this and here is my findings for the same.

**How Subscriptions work with Payfast Payment Gateway:**
The plugin uses **Tokenization** (ad-hoc) to process subscription payments. When customer signup for a subscription and pays using Payfast payment gateway, a token generated using Tokenization for subscription and that token is utilized during the subscription renewal to charge the customer. Also, when a customer cancels the subscription, the token also gets cancelled on the Payfast side. Cancellation works from both the WooCommerce store and the PayFast side. If you cancel at the store, the token is cancelled at PayFast. If you cancel at PayFast, the subscription gets cancelled at WooCommerce store.

**Support for Multiple Subscriptions:**
Support for Multiple Subscriptions allows customers to purchase multiple subscriptions in one transaction, also it groups the subscriptions with the same billing schedule. As purchases happen in one transaction, a single token gets generated by Payfast for multiple subscriptions. 

For example, if a customer purchases 2 x monthly subscriptions and 3 x yearly subscriptions in one transaction, 2 x subscriptions would be created – one with line items for the monthly subscription products and one with line items for the annual subscription products, and both subscriptions will have a common **token** from Payfast to process renewal payments.

Now, If a customer or merchant cancel any one subscription from these two, then it will cancel the token at the Payfast side and renewal payments for other subscriptions will be stopped, customer has to manually renew and update the payment method of other subscription to enable automatic renewal on it.

We can add a check at WooCommerce store side to not cancel the token if any other subscription is connected with the same token, but as mentioned above token can be cancelled at the Payfast side as well (by merchant and customer both). So, if the token gets cancelled at Payfast side by the merchant or customer to stop any single subscription then all connected subscriptions will be stopped and require manual action to re-enable auto-renewal on needed subscriptions to keep them active. However, Maybe cancellation at the Payfast side is not a common use case and is mostly not used by customers and merchants but as we don't have data on how much it is used we still have to consider this possibility. (Note: at sandbox account dashboard, I didn't find a way to trigger ITN on cancel token at Payfast side) 

In my opinion, We shouldn't add support for multiple subscriptions as of now, as we have a very low number of reports requesting this feature, and the way we can add support for multiple subscriptions in Payfast is not optimal (multiple subscriptions connected to a single token). @dkotter @jeffpaul I would like to hear from you for your suggestions and thoughts on this.

Thanks

**Comment by dkotter** [comment]
@iamdharmesh This sounds like the correct conclusion based on what you've found. Just to clarify one point, is it Payfast that is creating a single token for multiple subscriptions, or is that something we could theoretically change within the extension?

**Comment by iamdharmesh** [comment]
> Just to clarify one point, is it Payfast that is creating a single token for multiple subscriptions, or is that something we could theoretically change within the extension?

@dkotter Payfast generates a token per transaction. As in multiple subscriptions support, multiple subscriptions are added to the cart and purchased under a single order and transaction. So, all subscriptions will have one common token. To generate a separate token for each subscription we have to make payment for all subscriptions separately, which is already current behavior and blocks us to add support for multiple subscriptions.

**Comment by dkotter** [comment]
Since this seems like a limitation of Payfast and not the gateway, going to close this issue out.
