### ISSUE TITLE
TLS Termination on May 1, 2022

### ISSUE THREAD

**Issue by rynaldos** [woocommerce/woocommerce-gateway-payfast#77]
A user received the following notification from PayFast in regard to an upcoming TLS termination, which I would like to raise here just in case it needs our attention and if any changes are needed in the PayFast extension. The email is as follows. 

<img width="353" alt="Screenshot 2022-04-05 at 10 01 54" src="https://user-images.githubusercontent.com/89896100/161707680-ba20ae2f-713b-4da3-a7f8-1cb5d4a3fa67.png">

**Comment by iamdharmesh** [comment]
Hi @rynaldos,

Thanks for raising this. There are no changes required in the PayFast extension, As TLS stuff is handled at the server level, and the extension use wp core's request functions to call PayFast API, it doesn't require any code-level changes for this.
Also, I tested the plugin with sandbox env as suggested in the email screenshot, and it working fine.

So, we are good to go with closing this. @dkotter @jeffpaul please help with closing this.

Thanks.
