### ISSUE TITLE
Test against Custom Order Table implementation

### ISSUE THREAD

**Issue by vikrampm1** [woocommerce/woocommerce-gateway-payfast#98]
Describe the request
Please review the [Custom Order Table testing guide](https://developer.woocommerce.com/2022/05/16/call-for-early-testing-custom-order-table-migrations/), [upgrade guide](https://github.com/woocommerce/woocommerce/wiki/COT-Upgrade-Recipe-Book), and utilize the [latest testing ZIP](https://github.com/woocommerce/woocommerce/releases/tag/feature-custom-order-table) to see how the WooCommerce Core COT migration impacts the Payfast extension. If you run into questions, @alefesouza at WooCommerce will be the best person to reach out to while testing this migration on Payfast.

If things test smoothly, please leave a comment to that extent with any details of your testing.

If you run into issues, please document those here so that we can work with @alefesouza and the https://github.com/orgs/woocommerce/teams/proton team to determine if fixes are needed in WooCommerce core, Payfast, or both.

Testing approach:

Smoke test backend (wp-admin/management screens) interfaces to ensure they continue to work as expected.
Smoke test frontend functionality with Twenty Twenty-Two or Storefront.
By the nature of this project, think of any feature that might be related to how orders are stored in the database and prioritize testing that.

**Comment by cadic** [comment]
The migration of Payfast orders to custom order tables works well. Creating new orders fails because of multiple occurrences of old-style post meta functions, converted to WC_Order meta functions in #99
